import requests
import pandas as pd
from bs4 import BeautifulSoup  

# check the status code to start as a habit

# header to say I am a browser and not some generic script
headers = {
    "User-Agent": "Mozilla/5.0"
}

url = "https://www.espn.com/nfl/stats/team/_/view/offense/stat/rushing/season/2025/seasontype/2/table/rushing/sort/rushingYardsPerGame/dir/desc"

def get_stats(url, headers):
    response = requests.get(url, headers=headers)

    if response.status_code != 200:
        print("Unable to retrieve stats")
        print(response.status_code)

    soup = BeautifulSoup(response.content, "html.parser")

    team_column_header = soup.find("thead").text
    stats_column_header = soup.find_all("div", class_="Table__sub-header Table__TR Table__even")
    print(team_column_header)
    print(stats_column_header)

# <thead class="Table__header-group Table__THEAD"><tr class="Table__sub-header Table__TR Table__even"><th title="" class="Table__TH"><span class="underline" title="Games Played"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/general/sort/gamesPlayed/dir/desc">GP</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Attempts"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingAttempts/dir/desc">ATT</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Yards"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingYards/dir/desc">YDS</a></span></th><th title="" class="Table__TH"><span class="underline" title="Yards Per Rush Attempt"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/yardsPerRushAttempt/dir/desc">AVG</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Yards Per Game"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingYardsPerGame/dir/asc">YDS/G<svg aria-hidden="true" class="ArrowIcon__TableSort icon__svg" style="display:inline-block;height:10px;width:10px;margin-left:4px" viewBox="0 0 24 24"><use xlink:href="#icon__caret__down"></use></svg></a></span></th><th title="" class="Table__TH"><span class="underline" title="Long Rushing"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/longRushing/dir/desc">LNG</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Touchdowns"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingTouchdowns/dir/desc">TD</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Fumbles"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingFumbles/dir/desc">FUM</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Fumbles Lost"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingFumblesLost/dir/desc">LST</a></span></th></tr></thead>
get_stats(url, headers) 
#  <tr class="Table__sub-header Table__TR Table__even"><th title="" class="Table__TH"><span class="underline" title="Games Played"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/general/sort/gamesPlayed/dir/desc">GP</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Attempts"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingAttempts/dir/desc">ATT</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Yards"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingYards/dir/desc">YDS</a></span></th><th title="" class="Table__TH"><span class="underline" title="Yards Per Rush Attempt"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/yardsPerRushAttempt/dir/desc">AVG</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Yards Per Game"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingYardsPerGame/dir/asc">YDS/G<svg aria-hidden="true" class="ArrowIcon__TableSort icon__svg" style="display:inline-block;height:10px;width:10px;margin-left:4px" viewBox="0 0 24 24"><use xlink:href="#icon__caret__down"></use></svg></a></span></th><th title="" class="Table__TH"><span class="underline" title="Long Rushing"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/longRushing/dir/desc">LNG</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Touchdowns"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingTouchdowns/dir/desc">TD</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Fumbles"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingFumbles/dir/desc">FUM</a></span></th><th title="" class="Table__TH"><span class="underline" title="Rushing Fumbles Lost"><a class="AnchorLink clr-gray-01" tabindex="0" href="/nfl/stats/team/_/view/offense/season/2025/seasontype/2/stat/rushing/table/rushing/sort/rushingFumblesLost/dir/desc">LST</a></span></th></tr>